sync

diff --git a/tools/callgraph b/tools/callgraph
--- a/tools/callgraph
+++ b/tools/callgraph
@@ -22,11 +22,7 @@
 OS=$(uname)
 
 # Tree2Dot
-if [ "x$OS" == "xDarwin" ]; then
-    TOP_DIR=$(dirname $0)/
-else
-    TOP_DIR=$(dirname `readlink -f $0`)/
-fi
+TOP_DIR=$(cd $(dirname $0) && pwd)/
 tree2dotx=${TOP_DIR}/tree2dotx
 
 # Output directory
@@ -140,18 +136,18 @@ tmp=`echo $file | tr '/' '_' | tr '.' '_'`
 pic=${func}.${tmp}.${PIC_TYPE}
 long_pic=${OUT_DIR}/${pic}
 
-which cflow 2>&1 > /dev/null
+which cflow >/dev/null 2>&1
 if [ $? -ne 0 ]; then
-        echo "Note: cflow doesn't exist, please install it..."
-        sleep 2
-        echo "Note: Use calltree instead for this test."
-        sleep 2
-        [ -n "$depth" ] && depth="depth=$depth"
-        calltree="${TOP_DIR}/calltree -b -np $depth list="
+        echo "Error: cflow doesn't exist, please install it..."
+        exit 1
 else
         [ -n "$depth" ] && depth=" -d $depth "
         calltree="cflow -b $depth -m "
 fi
+
+which dot >/dev/null 2>&1
+[ $? -ne 0 ] && "Error: dot doesn't exist, please install graphviz..."
+
 echo "Command: ${calltree}${func} ${file} | ${tree2dotx} "${filterstr}" 2>/dev/null | dot -T${PIC_TYPE} -o $long_pic"
 ${calltree}${func} ${file} | ${tree2dotx} -f "${filterstr}" 2>/dev/null | dot -T${PIC_TYPE} -o $long_pic
 
@@ -159,6 +155,6 @@ ${calltree}${func} ${file} | ${tree2dotx} -f "${filterstr}" 2>/dev/null | dot -T
 echo "Target: ${file}: ${func} -> ${long_pic}"
 
 # Display it
-which $BROWSER 2>&1 > /dev/null
+which $BROWSER >/dev/null 2>&1
 [ $? -ne 0 ] && exit 0
 $BROWSER ${long_pic} &
